name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zeroistfilm/svelte-chart:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted #pass-analysis #EC2 Label
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker run

        run: |
          docker stop svelte-chart
          docker rm svelte-chart
          docker rmi zeroistfilm/svelte-chart:latest
          docker run -d -p 8081:8081 --name svelte-chart --restart always zeroistfilm/svelte-chart:latest
