name: GitHub Actions Demo
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        node-version: [ 16.x ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
      - run: npm run build




#      - name: Cache yarn dependencies
#        uses: actions/cache@v1
#        id: yarn-cache
#        with:
#          path: node_modules
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-